2024-11-14 13:22:37,255 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:22:56,050 - INFO: -------------------------
2024-11-14 13:22:56,051 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:22:56,053 - INFO: -------------------------
2024-11-14 13:22:56,081 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:22:56,208 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:22:56,613 - ERROR: Invalid transport for session _OIGpjlTawwnwxuZAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:23:01,214 - DEBUG: 14 BLE-Devices found
2024-11-14 13:23:04,635 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:23:04,636 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:23:25,370 - INFO: -------------------------
2024-11-14 13:23:25,400 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:23:25,420 - INFO: -------------------------
2024-11-14 13:23:25,473 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:23:25,615 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:23:26,145 - ERROR: Invalid transport for session Hmn8tkMASnYmmwLXAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:23:30,628 - DEBUG: 12 BLE-Devices found
2024-11-14 13:24:16,380 - INFO: -------------------------
2024-11-14 13:24:16,380 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:24:16,381 - INFO: -------------------------
2024-11-14 13:24:16,394 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:24:16,481 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:24:16,712 - ERROR: Invalid session qWCQ_dRU4OYnN5ZiAAAG (further occurrences of this error will be logged with level INFO)
2024-11-14 13:24:17,025 - ERROR: Invalid transport for session uVtp88gay1IDh8_JAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:24:21,504 - DEBUG: 12 BLE-Devices found
2024-11-14 13:25:04,065 - INFO: -------------------------
2024-11-14 13:25:04,066 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:25:04,067 - INFO: -------------------------
2024-11-14 13:25:04,077 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:25:04,159 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:25:05,701 - ERROR: Invalid transport for session yo1JpHEUP6ix45MRAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:25:09,184 - DEBUG: 14 BLE-Devices found
2024-11-14 13:25:48,450 - INFO: -------------------------
2024-11-14 13:25:48,450 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:25:48,452 - INFO: -------------------------
2024-11-14 13:25:48,464 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:25:48,549 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:25:48,964 - ERROR: Invalid transport for session Lj9jQjHuS3cfnusNAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:25:53,573 - DEBUG: 12 BLE-Devices found
2024-11-14 13:25:56,812 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:25:56,812 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:30:42,720 - INFO: -------------------------
2024-11-14 13:30:42,720 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:30:42,721 - INFO: -------------------------
2024-11-14 13:30:42,734 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:30:42,815 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:30:43,356 - ERROR: Invalid transport for session O8UVPwu1NaJ-DsQXAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:30:47,837 - DEBUG: 12 BLE-Devices found
2024-11-14 13:31:11,697 - INFO: -------------------------
2024-11-14 13:31:11,697 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:31:11,699 - INFO: -------------------------
2024-11-14 13:31:11,710 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:31:11,794 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:31:12,596 - ERROR: Invalid transport for session mQmudOt4Q97GspaIAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:31:16,793 - DEBUG: 16 BLE-Devices found
2024-11-14 13:31:26,961 - INFO: -------------------------
2024-11-14 13:31:26,962 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:31:26,962 - INFO: -------------------------
2024-11-14 13:31:26,973 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:31:27,049 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:31:27,144 - ERROR: Invalid session nIm6hrFKNyLkipXHAAAC (further occurrences of this error will be logged with level INFO)
2024-11-14 13:31:27,710 - ERROR: Invalid transport for session 0X7Vb6u4Ccmu159yAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:31:32,078 - DEBUG: 14 BLE-Devices found
2024-11-14 13:32:37,068 - DEBUG: 15 BLE-Devices found
2024-11-14 13:33:18,288 - INFO: -------------------------
2024-11-14 13:33:18,289 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:33:18,289 - INFO: -------------------------
2024-11-14 13:33:18,306 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:33:18,420 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:33:18,980 - ERROR: Invalid transport for session 53wZXl0u0tAKgsYVAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:33:23,421 - DEBUG: 15 BLE-Devices found
2024-11-14 13:33:28,504 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:33:28,505 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:33:53,253 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:33:53,253 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:34:10,275 - INFO: -------------------------
2024-11-14 13:34:10,276 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:34:10,277 - INFO: -------------------------
2024-11-14 13:34:10,289 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:34:10,494 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:34:12,096 - ERROR: Invalid transport for session Jmy1rLgXE6qeOjf6AAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:34:15,493 - DEBUG: 15 BLE-Devices found
2024-11-14 13:35:20,526 - DEBUG: 17 BLE-Devices found
2024-11-14 13:36:25,569 - DEBUG: 11 BLE-Devices found
2024-11-14 13:37:30,582 - DEBUG: 17 BLE-Devices found
2024-11-14 13:38:22,770 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:38:22,771 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:38:35,580 - DEBUG: 15 BLE-Devices found
2024-11-14 13:38:36,093 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:38:36,095 - INFO: Car Virtual Vehicle 2 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:39:23,006 - INFO: Car Virtual Vehicle 1 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 13:39:36,373 - INFO: Car Virtual Vehicle 2 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 13:39:40,621 - DEBUG: 14 BLE-Devices found
2024-11-14 13:39:41,007 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:39:41,008 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:47:49,654 - INFO: -------------------------
2024-11-14 13:47:49,654 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:47:49,655 - INFO: -------------------------
2024-11-14 13:47:49,664 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:47:49,745 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:47:52,093 - ERROR: Invalid transport for session J8Q2SzkZ_n7sS5CRAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:47:54,767 - DEBUG: 15 BLE-Devices found
2024-11-14 13:47:59,509 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:47:59,510 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:48:01,181 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2171' coro=<StaffUI.__emit_new_data() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py:628> exception=TypeError('Object of type method is not JSON serializable')>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py", line 637, in __emit_new_data
    await self._sio.emit('update_uuids', data)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 178, in emit
    await self.manager.emit(event, data, namespace, room=room,
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_manager.py", line 39, in emit
    encoded_packet = pkt.encode()
                     ^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2024-11-14 13:48:01,254 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2172' coro=<StaffUI.__emit_new_data() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py:628> exception=TypeError('Object of type method is not JSON serializable')>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py", line 637, in __emit_new_data
    await self._sio.emit('update_uuids', data)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 178, in emit
    await self.manager.emit(event, data, namespace, room=room,
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_manager.py", line 39, in emit
    encoded_packet = pkt.encode()
                     ^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2024-11-14 13:48:01,346 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-2260' coro=<StaffUI.__emit_new_data() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py:628> exception=TypeError('Object of type method is not JSON serializable')>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\UserInterface\StaffUI.py", line 637, in __emit_new_data
    await self._sio.emit('update_uuids', data)
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_server.py", line 178, in emit
    await self.manager.emit(event, data, namespace, room=room,
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\async_manager.py", line 39, in emit
    encoded_packet = pkt.encode()
                     ^^^^^^^^^^^^
  File "C:\Users\mariok\.virtualenvs\IAV_Distortion-8tpuzdpM\Lib\site-packages\socketio\packet.py", line 64, in encode
    encoded_packet += self.json.dumps(data, separators=(',', ':'))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type method is not JSON serializable
2024-11-14 13:48:59,762 - DEBUG: 12 BLE-Devices found
2024-11-14 13:48:59,947 - INFO: Car Virtual Vehicle 1 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 13:49:23,545 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:49:23,546 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:50:04,750 - DEBUG: 18 BLE-Devices found
2024-11-14 13:50:24,242 - INFO: Car Virtual Vehicle 1 doesn't have the effect VehicleEffectIdentification.HACKING_PROTECTION anymore
2024-11-14 13:50:38,215 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:50:38,216 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:51:09,772 - DEBUG: 16 BLE-Devices found
2024-11-14 13:51:32,837 - INFO: -------------------------
2024-11-14 13:51:32,837 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:51:32,838 - INFO: -------------------------
2024-11-14 13:51:32,848 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:51:32,928 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:51:34,232 - ERROR: Invalid transport for session MXnFZp7qdlADTPhEAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:51:37,949 - DEBUG: 15 BLE-Devices found
2024-11-14 13:53:42,443 - INFO: -------------------------
2024-11-14 13:53:42,445 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:53:42,447 - INFO: -------------------------
2024-11-14 13:53:42,462 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:53:42,561 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:53:42,919 - ERROR: Invalid transport for session 1u9gkLwV__LFH17GAAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:53:47,570 - DEBUG: 15 BLE-Devices found
2024-11-14 13:53:52,988 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:53:52,989 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:54:03,954 - INFO: Removing vehicle with UUID Virtual Vehicle 4
2024-11-14 13:54:08,634 - ERROR: Task exception was never retrieved
future: <Task finished name='Task-4732' coro=<Bot._drive_automatically() done, defined at C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py:18> exception=AttributeError("'NoneType' object has no attribute 'speed_request'")>
Traceback (most recent call last):
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 34, in _drive_automatically
    action()
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\BotManagement\Bot.py", line 24, in <lambda>
    1: lambda: self._behaviour_ctrl.request_speed_change_for(uuid=self.vehicle, value_perc=random_speed),
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariok\IdeaProjects\IAV Distortion\IAV_Distortion\src\VehicleMovementManagement\BehaviourController.py", line 30, in request_speed_change_for
    vehicle.speed_request = value_perc
    ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'speed_request'
2024-11-14 13:54:08,983 - ERROR: Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\mariok\AppData\Local\Programs\Python\Python311\Lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2024-11-14 13:54:21,868 - INFO: -------------------------
2024-11-14 13:54:21,868 - INFO:  STARTING IAV-Distortion 
2024-11-14 13:54:21,869 - INFO: -------------------------
2024-11-14 13:54:21,879 - INFO: Auto discovery service for Anki cars activated.
2024-11-14 13:54:21,954 - INFO: Running on http://0.0.0.0:5000 (CTRL + C to quit)
2024-11-14 13:54:23,349 - ERROR: Invalid transport for session vDE6Fqb4RqngT620AAAA (further occurrences of this error will be logged with level INFO)
2024-11-14 13:54:26,954 - DEBUG: 15 BLE-Devices found
2024-11-14 13:54:40,243 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.HACKING_PROTECTION
2024-11-14 13:54:40,244 - INFO: Car Virtual Vehicle 1 now has the effect VehicleEffectIdentification.CLEAN_HACKED_EFFECTS
2024-11-14 13:54:43,135 - INFO: Removing vehicle with UUID Virtual Vehicle 1
